/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Alejandro
 */
public class VentanaRegistroVenta extends javax.swing.JFrame {

    /**
     * Creates new form VentanaRegistroVenta
     */
    public VentanaRegistroVenta() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/Logo Ventana.png")).getImage());
        Icon miIcono = new ImageIcon(new ImageIcon(getClass().getResource("/Iconos/IconoSinFondo.png")).getImage().getScaledInstance(LabelImagen4.getWidth(), LabelImagen4.getHeight(), 0));
        LabelImagen4.setIcon(miIcono);
        ActualizarAparienciaBoton();
        
        
        CampoCedulaCliente.getDocument().addDocumentListener(new FieldListener());
        CampoNombreVendedor.getDocument().addDocumentListener(new FieldListener());
        CampoNoCuotas.getDocument().addDocumentListener(new FieldListener());
        CampoFechaEscritura.getDocument().addDocumentListener(new FieldListener());
        
    }

    private void revisarCampos() {
        boolean camposLlenos = !CampoCedulaCliente.getText().trim().isEmpty() &&
                               !CampoNombreVendedor.getText().trim().isEmpty() &&
                               !CampoNoCuotas.getText().trim().isEmpty() &&
                               !CampoFechaEscritura.getText().trim().isEmpty();

        // Activa o desactiva el botón de registrar según el estado de los campos
        BotonRegistrar.setEnabled(camposLlenos);
        ActualizarAparienciaBoton();
    }
    
    
    
    private class FieldListener implements DocumentListener {
        @Override
        public void insertUpdate(DocumentEvent e) {
            revisarCampos();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            revisarCampos();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            revisarCampos();
        }
    }

   
    
    
      private void ActualizarAparienciaBoton() {
        if (!BotonRegistrar.isEnabled()) {
            BotonRegistrar.setBackground(Color.GRAY); // Color de fondo gris
            BotonRegistrar.setForeground(new Color(100,100,100)); // Color de texto negro
        } else {
            BotonRegistrar.setBackground(new Color(0, 51, 102)); // Color de fondo original
            BotonRegistrar.setForeground(Color.WHITE); // Color de texto original
        }
        BotonRegistrar.repaint();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        PanelRegistroVenta = new javax.swing.JPanel();
        PanelLateralVenta = new javax.swing.JPanel();
        LabelImagen4 = new javax.swing.JLabel();
        BotonRegresar2 = new javax.swing.JButton();
        LabelRegistroVenta = new javax.swing.JLabel();
        PanelInfoVenta = new javax.swing.JPanel();
        LabelTorre2 = new javax.swing.JLabel();
        LabelProyecto2 = new javax.swing.JLabel();
        LabelApartamento = new javax.swing.JLabel();
        CampoCedulaCliente = new javax.swing.JTextField();
        CampoNombreVendedor = new javax.swing.JTextField();
        CampoNoCuotas = new javax.swing.JTextField();
        CampoFechaEscritura = new javax.swing.JTextField();
        LabelCedCliente = new javax.swing.JLabel();
        LabelFechaEscritura = new javax.swing.JLabel();
        LabelNomVendedor = new javax.swing.JLabel();
        LavelNumCuotas = new javax.swing.JLabel();
        LabelTasaInt = new javax.swing.JLabel();
        BotonRegistrar = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nombre del Vendedor*");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Urbaniza - Registro de Venta");
        setResizable(false);

        PanelRegistroVenta.setBackground(new java.awt.Color(255, 255, 255));
        PanelRegistroVenta.setPreferredSize(new java.awt.Dimension(1400, 800));

        PanelLateralVenta.setBackground(new java.awt.Color(240, 240, 240));
        PanelLateralVenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        BotonRegresar2.setBackground(new java.awt.Color(240, 240, 240));
        BotonRegresar2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        BotonRegresar2.setText("← Regresar");
        BotonRegresar2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        BotonRegresar2.setContentAreaFilled(false);
        BotonRegresar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLateralVentaLayout = new javax.swing.GroupLayout(PanelLateralVenta);
        PanelLateralVenta.setLayout(PanelLateralVentaLayout);
        PanelLateralVentaLayout.setHorizontalGroup(
            PanelLateralVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLateralVentaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelLateralVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BotonRegresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelImagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PanelLateralVentaLayout.setVerticalGroup(
            PanelLateralVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLateralVentaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LabelImagen4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                .addComponent(BotonRegresar2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        LabelRegistroVenta.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 30)); // NOI18N
        LabelRegistroVenta.setText("REGISTRAR UNA VENTA");

        PanelInfoVenta.setBackground(new java.awt.Color(240, 240, 240));
        PanelInfoVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        LabelTorre2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 26)); // NOI18N
        LabelTorre2.setForeground(new java.awt.Color(51, 51, 51));
        LabelTorre2.setText("Torre:");

        LabelProyecto2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 26)); // NOI18N
        LabelProyecto2.setForeground(new java.awt.Color(51, 51, 51));
        LabelProyecto2.setText("Proyecto:");

        LabelApartamento.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 26)); // NOI18N
        LabelApartamento.setForeground(new java.awt.Color(51, 51, 51));
        LabelApartamento.setText("Apartamento: ");

        javax.swing.GroupLayout PanelInfoVentaLayout = new javax.swing.GroupLayout(PanelInfoVenta);
        PanelInfoVenta.setLayout(PanelInfoVentaLayout);
        PanelInfoVentaLayout.setHorizontalGroup(
            PanelInfoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoVentaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelInfoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTorre2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelProyecto2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        PanelInfoVentaLayout.setVerticalGroup(
            PanelInfoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoVentaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(LabelProyecto2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelTorre2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        CampoCedulaCliente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        CampoCedulaCliente.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        CampoCedulaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCedulaClienteActionPerformed(evt);
            }
        });

        CampoNombreVendedor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        CampoNombreVendedor.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        CampoNombreVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNombreVendedorActionPerformed(evt);
            }
        });

        CampoNoCuotas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        CampoNoCuotas.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        CampoNoCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNoCuotasActionPerformed(evt);
            }
        });

        CampoFechaEscritura.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        CampoFechaEscritura.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        CampoFechaEscritura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoFechaEscrituraActionPerformed(evt);
            }
        });

        LabelCedCliente.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        LabelCedCliente.setForeground(new java.awt.Color(51, 51, 51));
        LabelCedCliente.setText("Cedula del Cliente*");

        LabelFechaEscritura.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        LabelFechaEscritura.setForeground(new java.awt.Color(51, 51, 51));
        LabelFechaEscritura.setText("Fecha de Escritura*");

        LabelNomVendedor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        LabelNomVendedor.setForeground(new java.awt.Color(51, 51, 51));
        LabelNomVendedor.setText("Nombre del Vendedor*");

        LavelNumCuotas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        LavelNumCuotas.setForeground(new java.awt.Color(51, 51, 51));
        LavelNumCuotas.setText("Numero de Cuotas*");

        LabelTasaInt.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        LabelTasaInt.setForeground(new java.awt.Color(51, 51, 51));
        LabelTasaInt.setText("Tasa de Interés:    ");
        LabelTasaInt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));

        BotonRegistrar.setBackground(new java.awt.Color(0, 51, 102));
        BotonRegistrar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        BotonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegistrar.setText("REGISTRAR");
        BotonRegistrar.setBorder(null);
        BotonRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegistrar.setEnabled(false);
        BotonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRegistroVentaLayout = new javax.swing.GroupLayout(PanelRegistroVenta);
        PanelRegistroVenta.setLayout(PanelRegistroVentaLayout);
        PanelRegistroVentaLayout.setHorizontalGroup(
            PanelRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroVentaLayout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addGroup(PanelRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroVentaLayout.createSequentialGroup()
                        .addComponent(LabelRegistroVenta)
                        .addGap(352, 352, 352))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroVentaLayout.createSequentialGroup()
                        .addGroup(PanelRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoFechaEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelCedCliente)
                            .addComponent(LabelFechaEscritura)
                            .addComponent(LabelTasaInt, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelRegistroVentaLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(PanelRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CampoNoCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CampoNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LavelNumCuotas)
                                    .addComponent(LabelNomVendedor)))
                            .addGroup(PanelRegistroVentaLayout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroVentaLayout.createSequentialGroup()
                        .addComponent(PanelInfoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(308, 308, 308)))
                .addComponent(PanelLateralVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        PanelRegistroVentaLayout.setVerticalGroup(
            PanelRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroVentaLayout.createSequentialGroup()
                .addGroup(PanelRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroVentaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(PanelLateralVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRegistroVentaLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(LabelRegistroVenta)
                        .addGap(59, 59, 59)
                        .addComponent(PanelInfoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(PanelRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNomVendedor)
                            .addComponent(LabelCedCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(PanelRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelFechaEscritura)
                            .addComponent(LavelNumCuotas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CampoFechaEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoNoCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(PanelRegistroVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTasaInt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRegistroVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRegistroVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoCedulaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCedulaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCedulaClienteActionPerformed

    private void CampoNombreVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNombreVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNombreVendedorActionPerformed

    private void CampoNoCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNoCuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNoCuotasActionPerformed

    private void CampoFechaEscrituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoFechaEscrituraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoFechaEscrituraActionPerformed

    private void BotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarActionPerformed
        int variable = 2;
        if (variable == 1){
        Image imagenVentaExitosa = new ImageIcon(getClass().getResource("/iconos/VentaExitosa.png")).getImage();
        Image imagenRedimensionada = imagenVentaExitosa.getScaledInstance(70, 70, Image.SCALE_SMOOTH);
        ImageIcon iconoVentaExitosa = new ImageIcon(imagenRedimensionada);
        JOptionPane.showMessageDialog(this, "Se ha realizado la venta exitosamente!", "Mensaje de Confirmación", JOptionPane.PLAIN_MESSAGE, iconoVentaExitosa);
        this.dispose();
        VentanaInicioAsesor VentanaAsesor = new VentanaInicioAsesor();
        VentanaAsesor.setVisible(true);}
        else{
            JOptionPane.showMessageDialog(this, "Error: El cliente ya tiene una venta activa!", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonRegistrarActionPerformed

    private void BotonRegresar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresar2ActionPerformed
       this.dispose();
       VentanaVentaApto VentaApto = new VentanaVentaApto();
       VentaApto.setVisible(true);
    }//GEN-LAST:event_BotonRegresar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistroVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistroVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegistrar;
    private javax.swing.JButton BotonRegresar2;
    private javax.swing.JTextField CampoCedulaCliente;
    private javax.swing.JTextField CampoFechaEscritura;
    private javax.swing.JTextField CampoNoCuotas;
    private javax.swing.JTextField CampoNombreVendedor;
    private javax.swing.JLabel LabelApartamento;
    private javax.swing.JLabel LabelCedCliente;
    private javax.swing.JLabel LabelFechaEscritura;
    private javax.swing.JLabel LabelImagen4;
    private javax.swing.JLabel LabelNomVendedor;
    private javax.swing.JLabel LabelProyecto2;
    private javax.swing.JLabel LabelRegistroVenta;
    private javax.swing.JLabel LabelTasaInt;
    private javax.swing.JLabel LabelTorre2;
    private javax.swing.JLabel LavelNumCuotas;
    private javax.swing.JPanel PanelInfoVenta;
    private javax.swing.JPanel PanelLateralVenta;
    private javax.swing.JPanel PanelRegistroVenta;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
