
package Vista;

import java.awt.Color;
import javax.swing.ImageIcon;

public class VentanaVentaApto extends javax.swing.JFrame {

    public VentanaVentaApto() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/Logo Ventana.png")).getImage());
        LabelProyecto.setOpaque(true);
        LabelTorre.setOpaque(true); 
        ActualizarAparienciaBoton();
    }
    
  
    
    private void ActualizarAparienciaBoton() {
        if (!BotonVender.isEnabled()) {
            BotonVender.setBackground(Color.GRAY); // Color de fondo gris
            BotonVender.setForeground(new Color(100,100,100)); // Color de texto negro
        } else {
            BotonVender.setBackground(new Color(0, 51, 102)); // Color de fondo original
            BotonVender.setForeground(Color.WHITE); // Color de texto original
        }
        BotonVender.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipalVenta = new javax.swing.JPanel();
        LabelApartamentos = new javax.swing.JLabel();
        LabelProyecto = new javax.swing.JLabel();
        LabelTorre = new javax.swing.JLabel();
        PanelInfo = new javax.swing.JPanel();
        LabelInfo = new javax.swing.JLabel();
        LabelArea = new javax.swing.JLabel();
        LabelValor = new javax.swing.JLabel();
        LabelTipoUnidad = new javax.swing.JLabel();
        BotonVender = new javax.swing.JButton();
        botontogle = new javax.swing.JToggleButton();
        BotonRegresar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Urbaniza - Venta de Apartamento");
        setResizable(false);

        PanelPrincipalVenta.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrincipalVenta.setPreferredSize(new java.awt.Dimension(1400, 800));

        LabelApartamentos.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 35)); // NOI18N
        LabelApartamentos.setText("  APARTAMENTOS");

        LabelProyecto.setBackground(new java.awt.Color(240, 240, 240));
        LabelProyecto.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 22)); // NOI18N
        LabelProyecto.setText("PROYECTO: ");
        LabelProyecto.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));

        LabelTorre.setBackground(new java.awt.Color(240, 240, 240));
        LabelTorre.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 22)); // NOI18N
        LabelTorre.setText("TORRE: ");
        LabelTorre.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));

        PanelInfo.setBackground(new java.awt.Color(238, 238, 238));
        PanelInfo.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));

        LabelInfo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 29)); // NOI18N
        LabelInfo.setText("ⓘ INFORMACIÓN DE LOS APTOS");

        LabelArea.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 26)); // NOI18N
        LabelArea.setText("AREA: ");

        LabelValor.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 26)); // NOI18N
        LabelValor.setText("VALOR: ");

        LabelTipoUnidad.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 26)); // NOI18N
        LabelTipoUnidad.setText("TIPO DE UNIDAD: ");

        javax.swing.GroupLayout PanelInfoLayout = new javax.swing.GroupLayout(PanelInfo);
        PanelInfo.setLayout(PanelInfoLayout);
        PanelInfoLayout.setHorizontalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelArea, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelInfo))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        PanelInfoLayout.setVerticalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(LabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelArea, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        BotonVender.setBackground(new java.awt.Color(0, 51, 102));
        BotonVender.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 20)); // NOI18N
        BotonVender.setForeground(new java.awt.Color(255, 255, 255));
        BotonVender.setText("VENDER ESTE APARTAMENTO");
        BotonVender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        BotonVender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVender.setEnabled(false);
        BotonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVenderActionPerformed(evt);
            }
        });

        botontogle.setText("201");
        botontogle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botontogleActionPerformed(evt);
            }
        });

        BotonRegresar1.setBackground(new java.awt.Color(240, 240, 240));
        BotonRegresar1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        BotonRegresar1.setText("← Regresar");
        BotonRegresar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        BotonRegresar1.setContentAreaFilled(false);
        BotonRegresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalVentaLayout = new javax.swing.GroupLayout(PanelPrincipalVenta);
        PanelPrincipalVenta.setLayout(PanelPrincipalVentaLayout);
        PanelPrincipalVentaLayout.setHorizontalGroup(
            PanelPrincipalVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalVentaLayout.createSequentialGroup()
                .addGroup(PanelPrincipalVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalVentaLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(LabelApartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelPrincipalVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelProyecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTorre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelPrincipalVentaLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(botontogle, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                        .addComponent(PanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalVentaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonVender, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
            .addGroup(PanelPrincipalVentaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BotonRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPrincipalVentaLayout.setVerticalGroup(
            PanelPrincipalVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalVentaLayout.createSequentialGroup()
                .addGroup(PanelPrincipalVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalVentaLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(PanelPrincipalVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelPrincipalVentaLayout.createSequentialGroup()
                                .addComponent(LabelProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LabelTorre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelApartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(PanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(PanelPrincipalVentaLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(botontogle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(BotonVender, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(BotonRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botontogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botontogleActionPerformed
        BotonVender.setEnabled(botontogle.isSelected());
        ActualizarAparienciaBoton();
    }//GEN-LAST:event_botontogleActionPerformed

    private void BotonVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVenderActionPerformed
      this.dispose();
       VentanaRegistroVenta VentanaRegistrov = new VentanaRegistroVenta();
       VentanaRegistrov.setVisible(true);
    }//GEN-LAST:event_BotonVenderActionPerformed

    private void BotonRegresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresar1ActionPerformed
        this.dispose();
        VentanaInicioAsesor VentaAsesor = new VentanaInicioAsesor();
        VentaAsesor.setVisible(true);

    }//GEN-LAST:event_BotonRegresar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVentaApto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVentaApto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVentaApto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVentaApto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVentaApto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegresar1;
    private javax.swing.JButton BotonVender;
    private javax.swing.JLabel LabelApartamentos;
    private javax.swing.JLabel LabelArea;
    private javax.swing.JLabel LabelInfo;
    private javax.swing.JLabel LabelProyecto;
    private javax.swing.JLabel LabelTipoUnidad;
    private javax.swing.JLabel LabelTorre;
    private javax.swing.JLabel LabelValor;
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JPanel PanelPrincipalVenta;
    private javax.swing.JToggleButton botontogle;
    // End of variables declaration//GEN-END:variables
}
